{% set name = "kosh" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/kosh/archive/v{{ version }}.tar.gz
  sha256: 6c2f1071ed4a7816ff002b4eda965754d395c917e48e1f5e18042242a4b825d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - llnl-sina >=1.11.0
    - networkx
    - numpy
    - matplotlib
    - scipy
    - h5py >=3
    - scikit-learn>=1.0.2
    - pandas
    - hdbscan
    - tqdm
  run:
    - python >=3.6
    - llnl-sina >=1.11.0
    - networkx
    - numpy
    - matplotlib
    - scipy
    - h5py >=3
    - scikit-learn>=1.0.2
    - pandas
    - hdbscan
    - tqdm

test:
  imports:
    - kosh
  commands:
    - pip check
    - kosh --help
  requires:
    - pip

about:
  home: https://github.com/LLNL/kosh
  summary: Kosh allows codes to store, query, share and manipulate data via an easy-to-use Python API. Kosh lies on top of Sina and as a result can use any database backend supported by Sina. In adition Kosh aims to make data access and sharing as simple as possible.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - doutriaux1
