{% set name = "kosh" %}
{% set version = "2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/kosh/archive/v{{ version }}.tar.gz
  sha256: 597ed5beb4c3c3675b4af15ee7bfb60a463d5bda2222cd927061737ed073d562

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - llnl-sina >=1.11.0
  run:
    - python >=3.6
    - llnl-sina >=1.11.0
    - networkx
    - numpy

test:
  imports:
    - kosh
  commands:
    - pip check
    - kosh --help
  requires:
    - pip

about:
  home: https://github.com/LLNL/kosh
  summary: Kosh allows codes to store, query, share and manipulate data via an easy-to-use Python API. Kosh lies on top of Sina and as a result can use any database backend supported by Sina. In adition Kosh aims to make data access and sharing as simple as possible.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - doutriaux1
