{% set name = "kosh" %}
{% set version = "1.2" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/LLNL/kosh/archive/v{{ version }}.tar.gz
    sha256: 5ad7e2bdec345747950499945d10408cdbd9c822151a968b0a705339505410bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - llnl-sina
  run:
    - python
    - llnl-sina
    - networkx
    - numpy

test:
  imports:
    - kosh
  commands:
    - pip check
    - kosh --help
    - init_sina.py --help
  requires:
    - pip

about:
    home:  https://github.com/LLNL/kosh
    summary: Kosh allows codes to store, query, share data via an easy-to-use Python API. Kosh lies on top of Sina and as a result can use any database backend supported by Sina. In adition Kosh aims to make data access and sharing as simple as possible.
    license: MIT
    license_file: LICENSE

extra:
    recipe-maintainers:
     - doutriaux1
