{% set name = "kosh" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/kosh/archive/v{{ version }}.tar.gz
  sha256: e0d97c93476930ccfe8ed892517439d555760d66d57f9a8e52459fb5910ba398

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - llnl-sina >=1.11.0
    - networkx
    - numpy
    - matplotlib-base
    - scipy
    - h5py >=3
    - scikit-learn >=1.0.2
    - pandas
    - hdbscan
    - tqdm
  run:
    - python >=3.6
    - llnl-sina >=1.11.0
    - networkx
    - numpy
    - matplotlib-base
    - scipy
    - h5py >=3
    - scikit-learn >=1.0.2
    - pandas
    - hdbscan
    - tqdm

test:
  imports:
    - kosh
  commands:
    - pip check
    - kosh --help
  requires:
    - pip

about:
  home: https://github.com/LLNL/kosh
  summary: Kosh allows codes to store, query, share and manipulate data via an easy-to-use Python API. Kosh lies on top of Sina and as a result can use any database backend supported by Sina. In adition Kosh aims to make data access and sharing as simple as possible.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - doutriaux1
